import mysql.connector

def get_db_connection():
    connection = mysql.connector.connect(
        host="svc.sel5.cloudtype.app",
        port=31200,
        user="mariadb",
        password="1234",
        database="mariadb"
    )
    return connection

def insert_initial_data():
    initial_data = [
        ("대한민국", "서울", "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg"),
        ("미국", "워싱턴 D.C.", "https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg"),
        ("일본", "도쿄", "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg"),
        ("프랑스", "파리", "https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg"),
        ("독일", "베를린", "https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg"),
        ("중국", "베이징", "https://upload.wikimedia.org/wikipedia/commons/0/0c/Flag_of_China.svg"),
        ("브라질", "브라질리아", "https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg"),
        ("캐나다", "오타와", "https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg"),
        ("호주", "캔버라", "https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg"),
        ("인도", "뉴델리", "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg"),
        ("러시아", "모스크바", "https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg"),
        ("영국", "런던", "https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg"),
        ("이탈리아", "로마", "https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg"),
        ("멕시코", "멕시코시티", "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg"),
        ("스페인", "마드리드", "https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg"),
        ("아르헨티나", "부에노스아이레스", "https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg"),
        ("남아프리카 공화국", "프리토리아", "https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg"),
        ("사우디아라비아", "리야드", "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg"),
        ("이집트", "카이로", "https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg"),
        ("터키", "앙카라", "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg"),
        ("스웨덴", "스톡홀름", "https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg"),
        ("노르웨이", "오슬로", "https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg"),
        ("핀란드", "헬싱키", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg"),
        ("덴마크", "코펜하겐", "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg"),
        ("폴란드", "바르샤바", "https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg"),
        ("체코", "프라하", "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg"),
        ("오스트리아", "빈", "https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg"),
        ("스위스", "베른", "https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg"),
        ("그리스", "아테네", "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg"),
        ("네덜란드", "암스테르담", "https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg"),
        ("벨기에", "브뤼셀", "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg"),
        ("포르투갈", "리스본", "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg"),
        ("이스라엘", "예루살렘", "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg"),
        ("아랍에미리트", "아부다비", "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg"),
        ("말레이시아", "쿠알라룸푸르", "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg"),
        ("싱가포르", "싱가포르", "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg"),
        ("태국", "방콕", "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg"),
        ("베트남", "하노이", "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg"),
        ("필리핀", "마닐라", "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg"),
        ("인도네시아", "자카르타", "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg"),
        ("뉴질랜드", "웰링턴", "https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg"),
        ("파키스탄", "이슬라마바드", "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg"),
        ("방글라데시", "다카", "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg"),
        ("스리랑카", "콜롬보", "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg"),
        ("네팔", "카트만두", "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg"),
        ("아프가니스탄", "카불", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg"),
        ("이란", "테헤란", "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg"),
        ("이라크", "바그다드", "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg"),
        ("시리아", "다마스쿠스", "https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg"),
        ("레바논", "베이루트", "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg"),
        ("요르단", "암만", "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg"),
        ("쿠웨이트", "쿠웨이트 시티", "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg"),
        ("카타르", "도하", "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg"),
        ("바레인", "마나마", "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg"),
        ("오만", "무스카트", "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg"),
        ("예멘", "사나", "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg"),
        ("북한", "평양", "https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg"),
        ("몽골", "울란바토르", "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg"),
        ("아이슬란드", "레이캬비크", "https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg"),
        ("아일랜드", "더블린", "https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg"),
        ("에스토니아", "탈린", "https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg"),
        ("라트비아", "리가", "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg"),
        ("리투아니아", "빌뉴스", "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg"),
        ("벨라루스", "민스크", "https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg"),
        ("우크라이나", "키예프", "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg"),
        ("몰도바", "키시너우", "https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Moldova.svg"),
        ("루마니아", "부쿠레슈티", "https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg"),
        ("불가리아", "소피아", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg"),
        ("세르비아", "베오그라드", "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg"),
        ("크로아티아", "자그레브", "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg"),
        ("보스니아 헤르체고비나", "사라예보", "https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg"),
        ("북마케도니아", "스코페", "https://upload.wikimedia.org/wikipedia/commons/f/f8/Flag_of_North_Macedonia.svg"),
        ("알바니아", "티라나", "https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg"),
        ("조지아", "트빌리시", "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg"),
        ("아르메니아", "예레반", "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg"),
        ("아제르바이잔", "바쿠", "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg"),
        ("카자흐스탄", "누르술탄", "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg"),
        ("우즈베키스탄", "타슈켄트", "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg"),
        ("투르크메니스탄", "아시가바트", "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg"),
        ("키르기스스탄", "비슈케크", "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg"),
        ("타지키스탄", "두샨베", "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg"),
        ("미얀마", "네피도", "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg"),
        ("라오스", "비엔티안", "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg"),
        ("캄보디아", "프놈펜", "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg"),
        ("브루나이", "반다르스리브가완", "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg"),
        ("동티모르", "딜리", "https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg"),
        ("타이완", "타이베이", "https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg"),
        ("피지", "수바", "https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg"),
        ("파푸아뉴기니", "포트모르즈비", "https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg"),
        ("솔로몬 제도", "호니아라", "https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg"),
        ("바누아투", "포트빌라", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg"),
        ("사모아", "아피아", "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg"),
        ("통가", "누쿠알로파", "https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Tonga.svg"),
        ("투발루", "푸나푸티", "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tuvalu.svg"),
        ("키리바시", "타라와", "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kiribati.svg"),
        ("나우루", "야렌", "https://upload.wikimedia.org/wikipedia/commons/3/30/Flag_of_Nauru.svg"),
        ("팔라우", "응게룰무드", "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Palau.svg"),
        ("미크로네시아 연방", "팔리키르", "https://upload.wikimedia.org/wikipedia/commons/e/e4/Flag_of_the_Federated_States_of_Micronesia.svg"),
        ("마셜 제도", "마주로", "https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg"),
        ("우간다", "캄팔라", "https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg"),
        ("케냐", "나이로비", "https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg"),
        ("탄자니아", "도도마", "https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Tanzania.svg"),
        ("르완다", "키갈리", "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg"),
        ("부룬디", "기테가", "https://upload.wikimedia.org/wikipedia/commons/5/5a/Flag_of_Burundi.svg"),
        ("콩고 민주 공화국", "킨샤사", "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg"),
        ("앙골라", "루안다", "https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg"),
        ("잠비아", "루사카", "https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg"),
        ("말라위", "릴롱궤", "https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg"),
        ("모잠비크", "마푸토", "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg"),
        ("마다가스카르", "안타나나리보", "https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg"),
        ("코모로", "모로니", "https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg"),
        ("세이셸", "빅토리아", "https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg"),
        ("모리셔스", "포트루이스", "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg"),
        ("레소토", "마세루", "https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg"),
        ("에스와티니", "음바바네", "https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg"),
        ("보츠와나", "가보로네", "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg"),
        ("짐바브웨", "하라레", "https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg"),
        ("나미비아", "빈트후크", "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg"),
        ("가봉", "리브르빌", "https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg"),
        ("카메룬", "야운데", "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg"),
        ("적도 기니", "말라보", "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg"),
        ("상투메 프린시페", "상투메", "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Sao_Tome_and_Principe.svg"),
        ("나이지리아", "아부자", "https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg"),
        ("베냉", "포르토노보", "https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg"),
        ("토고", "로메", "https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg"),
        ("가나", "아크라", "https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg"),
        ("코트디부아르", "야무수크로", "https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Ivory_Coast.svg"),
        ("부르키나파소", "와가두구", "https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg"),
        ("라이베리아", "몬로비아", "https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg"),
        ("시에라리온", "프리타운", "https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg"),
        ("기니", "코나크리", "https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg"),
        ("기니비사우", "비사우", "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg"),
        ("세네갈", "다카르", "https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg"),
        ("감비아", "반줄", "https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg"),
        ("모리타니아", "누악쇼트", "https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg"),
        ("말리", "바마코", "https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg"),
        ("니제르", "니아메", "https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg"),
        ("차드", "은자메나", "https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg"),
        ("중앙아프리카 공화국", "방기", "https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg"),
        ("남수단", "주바", "https://upload.wikimedia.org/wikipedia/commons/7/7a/Flag_of_South_Sudan.svg"),
        ("수단", "하르툼", "https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg"),
        ("에리트레아", "아스마라", "https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg"),
        ("지부티", "지부티", "https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg"),
        ("소말리아", "모가디슈", "https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg"),
        ("에티오피아", "아디스아바바", "https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg")
    ]

    connection = get_db_connection()
    cursor = connection.cursor()
    
    try:
        cursor.executemany(
            "INSERT INTO countries (country_name, capital_name, flag_url) VALUES (%s, %s, %s)", 
            initial_data
        )
        connection.commit()
        print("초기 데이터가 성공적으로 삽입되었습니다.")
    except mysql.connector.Error as err:
        print(f"데이터 삽입 오류: {err}")
    finally:
        cursor.close()
        connection.close()

if __name__ == '__main__':
    insert_initial_data()
